---
appendix: "appendix_1.Rmd"
---

# Simulating from models

Here's an example of how to simulate directly from a `lavaan` model:

```{r echo = T, eval = F, size = "small"}
# first build your model
# this example is separate for each group
model.invariant.g1 <- "
# loadings
lv =~ .8*q1 + .4*q2 + .6*q3 + .3*q4 + .6*q5 
# set the residual for invariance on q4
q4 ~~ 1*q4
# set the intercept for invariance on q4
q4 ~ 0*1
# set the intercept to zero for df purposes
q1 ~ 0*1
# allow the latent mean to be estimated 
lv ~ 1"
model.invariant.g2 <- "lv =~ .77*q1 + .43*q2 + .58*q3 + .3*q4 + .61*q5
q4 ~~ 1*q4
q4 ~ 0*1
q1 ~ 0*1
lv ~ 1"

# simulate data invariant separately for each group
df.invariant <- bind_rows(
  # lavaan function 
  simulateData(
    # model with estimates 
    model = model.invariant.g1, 
    # how many data points
    sample.nobs = 250, 
    # mean structure for mgcfa models 
    meanstructure = T, 
    # model type
    model.type = "cfa",
    # set seed for reproducibility 
    seed = 1234) %>% 
    # add a group label to the data 
    mutate(group = "Group 1"), 
  simulateData(
    model = model.invariant.g2, 
    sample.nobs = 250, 
    meanstructure = T, 
    model.type = "cfa",
    seed = 1234) %>% 
    mutate(group = "Group 2") 
)
```

\newpage

# Simulating from matrices

Here's an example of how to simulate using `MASS` and covariance or correlation matrices. 

```{r echo = T, eval = T, size = "small"}
library(MASS)

# covariance matrix
university.cov <- lav_matrix_lower2full(
    c(169.00, 
      73.710, 182.2500,
      73.229, 88.4250, 171.6100,
      63.375, 72.5625, 127.7250, 156.2500,
      42.120, 67.4325, 122.0265, 123.1875, 182.2500,
      57.226, 63.2610, 117.1926, 154.4250, 138.0240, 201.6400,
      30.875, 32.0625, 60.9805, 62.9375, 76.9500, 79.5910, 90.2500,
      36.075, 38.9610, 61.0722, 58.2750, 65.9340, 70.9290, 81.1965, 123.2100,
      18.096, 21.1410, 26.2131, 39.1500, 44.6310, 46.9452, 48.7635, 56.0106, 75.6900))

# give it names
rownames(university.cov) <-
    colnames(university.cov) <-
    c("class", "social", "learn", "chronic", "physical", "sex", 
      "depression", "anxiety", "stress")

# means - you need standard deviation if you only have a correlation matrix 
university.means <- c(3.4, 4.3, 3.7, 3.2, 4.5, 1.2, 4.0, 3.5, 4.2)

# use mass function
DF <- mvrnorm(n = 200, mu = university.means, Sigma = university.cov)

head(DF)
```

